jwt:
  secret: 1234567890123456789012345678901234567890123456789012345678901234
  expiration: 86400000

spring:
  datasource:
    username: sa
    password:

management:
  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

  endpoints:
    web:
      exposure:
        include: health,info,env,refresh,metrics,prometheus

logging:
  level:
    root: INFO