server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        native:
          search-locations: ${CONFIG_REPO_LOCATION:file:../config-repo}

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:native}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,refresh